// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWdlmG8EorwdfYYMOciHYg_TjqUTKop7w',
    appId: '1:942702798233:web:0b451d61adae05e4b71f08',
    messagingSenderId: '942702798233',
    projectId: 'eventico-8b5e6',
    authDomain: 'eventico-8b5e6.firebaseapp.com',
    storageBucket: 'eventico-8b5e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMBayzfWqen1gt9CYQ2oQHoeW6E39enA',
    appId: '1:942702798233:android:83d2f3eaaba3046cb71f08',
    messagingSenderId: '942702798233',
    projectId: 'eventico-8b5e6',
    storageBucket: 'eventico-8b5e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgShTsPLUjjUJMXPzMmKkMm6w37We6orI',
    appId: '1:942702798233:ios:9208a20164ff73ffb71f08',
    messagingSenderId: '942702798233',
    projectId: 'eventico-8b5e6',
    storageBucket: 'eventico-8b5e6.appspot.com',
    iosClientId: '942702798233-h9mvp32sqrqnfcr0m10s10fri7mq4ge3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgShTsPLUjjUJMXPzMmKkMm6w37We6orI',
    appId: '1:942702798233:ios:9208a20164ff73ffb71f08',
    messagingSenderId: '942702798233',
    projectId: 'eventico-8b5e6',
    storageBucket: 'eventico-8b5e6.appspot.com',
    iosClientId: '942702798233-h9mvp32sqrqnfcr0m10s10fri7mq4ge3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventico',
  );
}
